// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCDoctor.DataAccess.Data;

#nullable disable

namespace PCDoctor.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230822185251_AddProductToDb")]
    partial class AddProductToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCDoctor.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Mother Boards"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hard Disks"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "SSD"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "PC Peripherals"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "CPU Coolers"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Gaming Chairs"
                        });
                });

            modelBuilder.Entity("PCDoctor.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Core Count= 6, Clock Speed= 3.7GHz, Boost Speed= 4.6GHz, TDP=65W,Integrated Graphics=None",
                            Manufacturer = "Intel",
                            Name = "Intel Core i5-13600K",
                            Price = 345
                        },
                        new
                        {
                            Id = 2,
                            Description = "Core Count= 16, Clock Speed= 4.7GHz, Boost Speed= 6GHz, TDP=65W,Integrated Graphics=Intel UHD Graphics 770",
                            Manufacturer = "Intel",
                            Name = "Intel Core i9-13900K",
                            Price = 654
                        },
                        new
                        {
                            Id = 3,
                            Description = "Core Count= 6, Clock Speed= 4.2GHz, Boost Speed= 6GHz, TDP=65W,Integrated Graphics=Radeon",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 5 7600X",
                            Price = 343
                        },
                        new
                        {
                            Id = 4,
                            Description = "Core Count= 8, Clock Speed= 4.7GHz, Boost Speed= 5GHz, TDP=65W,Integrated Graphics=Intel UHD Graphics 770",
                            Manufacturer = "Intel",
                            Name = "Intel Core i7-13700K",
                            Price = 532
                        },
                        new
                        {
                            Id = 5,
                            Description = "Core Count= 8, Clock Speed= 3.7GHz, Boost Speed= 4GHz, TDP=120W,Integrated Graphics=Radeon",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 7 5800X",
                            Price = 245
                        },
                        new
                        {
                            Id = 6,
                            Description = "Core Count= 16, Clock Speed= 3.4GHz, Boost Speed= 3.4GHz, TDP=105W,Integrated Graphics=Radeon",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 435
                        },
                        new
                        {
                            Id = 7,
                            Description = "Core Count= 6, Clock Speed= 4.3GHz, Boost Speed= 4GHz, TDP=105W,Integrated Graphics=None",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 5 5600X",
                            Price = 100
                        },
                        new
                        {
                            Id = 8,
                            Description = "Core Count= 16, Clock Speed= 5.2GHz, Boost Speed= 6.7GHz, TDP=130W,Integrated Graphics=Intel UHD Graphics 770",
                            Manufacturer = "Intel",
                            Name = "Intel Core i7-12700K",
                            Price = 412
                        },
                        new
                        {
                            Id = 9,
                            Description = "Core Count= 8, Clock Speed= 4.7GHz, Boost Speed= 5GHz, TDP=65W,Integrated Graphics=Radeon",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 7 5700X",
                            Price = 242
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
