// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCDoctor.Data;

#nullable disable

namespace PCDoctor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230815195304_SeedDataIntoCategory")]
    partial class SeedDataIntoCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCDoctor.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Mother Boards"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hard Disks"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "SSD"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            Name = "CPU Cabinates"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
